# Don't change this! Version used to track needed updates.
version = 0
biomeColorRain = true

[biomes]
biomeParticlesRadius = 32
mushroomSporeBiomes = [
    "minecraft:mushroom_fields"
]
mushroomSporeDensity = 10
pollenBiomes = [
    "minecraft:flower_forest",
    "minecraft:sunflower_plains"
]
pollenDensity = 50
sculkDustBiomes = [
    "minecraft:deep_dark"
]
sculkDustDensity = 5

[geysers]
useUpdatedSmoke = false
flameGeyserSpawnChance = 5
flameGeyserSpawnableBlocks = [
    "minecraft:netherrack",
    "minecraft:blackstone",
    "minecraft:soul_soil"
]
flameGeyserSoundVolume = 0.5
flameGeyserActiveTime = 300
flameGeyserInactiveTime = 500
smokeGeyserSpawnChance = 5
smokeGeyserSpawnableBlocks = [
    "minecraft:netherrack",
    "minecraft:blackstone",
    "minecraft:soul_soil"
]
smokeGeyserSoundVolume = 0.2
smokeGeyserActiveTime = 300
smokeGeyserInactiveTime = 500
bubbleGeyserSpawnChance = 5
bubbleGeyserSpawnableBlocks = [
    "minecraft:sand",
    "minecraft:red_sand",
    "minecraft:gravel",
    "minecraft:dirt",
    "minecraft:clay"
]
bubbleGeyserSoundVolume = 0.5
bubbleGeyserActiveTime = 300
bubbleGeyserInactiveTime = 500

[fireflies]
firefliesEnabled = true
dimensionBlocklist = [
    "twilightforest:twilight_forest_type"
]
biomesBlocklist = [  ]
biomesAllowlist = [
    "minecraft:lush_caves"
]
spawnableBlocks = [
    "biomeswevegone:alpine_bellflower",
    "biomeswevegone:amaranth",
    "biomeswevegone:angelica",
    "biomeswevegone:begonia",
    "biomeswevegone:bistort",
    "biomeswevegone:black_rose",
    "biomeswevegone:blue_rose_bush",
    "biomeswevegone:blue_sage",
    "biomeswevegone:california_poppy",
    "biomeswevegone:crocus",
    "biomeswevegone:cyan_amaranth",
    "biomeswevegone:cyan_pitcher_plant",
    "biomeswevegone:cyan_rose",
    "biomeswevegone:cyan_tulip",
    "biomeswevegone:daffodil",
    "biomeswevegone:delphinium",
    "biomeswevegone:fairy_slipper",
    "biomeswevegone:flower_patch",
    "biomeswevegone:flowering_baobab_leaves",
    "biomeswevegone:flowering_barrel_cactus",
    "biomeswevegone:flowering_indigo_jacaranda_bush",
    "biomeswevegone:flowering_indigo_jacaranda_leaves",
    "biomeswevegone:flowering_ironwood_leaves",
    "biomeswevegone:flowering_jacaranda_bush",
    "biomeswevegone:flowering_jacaranda_leaves",
    "biomeswevegone:flowering_orchard_leaves",
    "biomeswevegone:flowering_palo_verde_leaves",
    "biomeswevegone:flowering_skyris_leaves",
    "biomeswevegone:flowering_tiny_lily_pads",
    "biomeswevegone:flowering_yucca_leaves",
    "biomeswevegone:foxglove",
    "biomeswevegone:green_tulip",
    "biomeswevegone:guzmania",
    "biomeswevegone:incan_lily",
    "biomeswevegone:iris",
    "biomeswevegone:japanese_orchid",
    "biomeswevegone:kovan_flower",
    "biomeswevegone:lazarus_bellflower",
    "biomeswevegone:lollipop_flower",
    "biomeswevegone:magenta_amaranth",
    "biomeswevegone:magenta_pitcher_plant",
    "biomeswevegone:magenta_tulip",
    "biomeswevegone:orange_amaranth",
    "biomeswevegone:orange_daisy",
    "biomeswevegone:osiria_rose",
    "biomeswevegone:peach_leather_flower",
    "biomeswevegone:pink_allium",
    "biomeswevegone:pink_anemone",
    "biomeswevegone:pink_daffodil",
    "biomeswevegone:protea_flower",
    "biomeswevegone:purple_amaranth",
    "biomeswevegone:purple_sage",
    "biomeswevegone:purple_tulip",
    "biomeswevegone:richea",
    "biomeswevegone:rose",
    "biomeswevegone:silver_vase_flower",
    "biomeswevegone:snowdrops",
    "biomeswevegone:tall_allium",
    "biomeswevegone:tall_pink_allium",
    "biomeswevegone:tall_white_allium",
    "biomeswevegone:violet_leather_flower",
    "biomeswevegone:white_allium",
    "biomeswevegone:white_anemone",
    "biomeswevegone:white_sage",
    "biomeswevegone:white_sakura_petals",
    "biomeswevegone:winter_cyclamen",
    "biomeswevegone:winter_rose",
    "biomeswevegone:winter_scilla",
    "biomeswevegone:yellow_daffodil",
    "biomeswevegone:yellow_sakura_petals",
    "biomeswevegone:yellow_tulip",
    "candlelight:rose",
    "cobblemon:pep_up_flower",
    "farm_and_charm:wild_barley",
    "farm_and_charm:wild_beetroots",
    "farm_and_charm:wild_carrots",
    "farm_and_charm:wild_corn",
    "farm_and_charm:wild_emmer",
    "farm_and_charm:wild_lettuce",
    "farm_and_charm:wild_nettle",
    "farm_and_charm:wild_oat",
    "farm_and_charm:wild_onions",
    "farm_and_charm:wild_potatoes",
    "farm_and_charm:wild_ribwort",
    "farm_and_charm:wild_strawberries",
    "farm_and_charm:wild_tomatoes",
    "farmersdelight:wild_beetroots",
    "farmersdelight:wild_cabbages",
    "farmersdelight:wild_carrots",
    "farmersdelight:wild_onions",
    "farmersdelight:wild_potatoes",
    "farmersdelight:wild_rice",
    "farmersdelight:wild_tomatoes",
    "herbalbrews:hibiscus",
    "herbalbrews:lavender",
    "minecraft:allium",
    "minecraft:azure_bluet",
    "minecraft:blue_orchid",
    "minecraft:cornflower",
    "minecraft:dandelion",
    "minecraft:flowering_azalea",
    "minecraft:lilac",
    "minecraft:lily_of_the_valley",
    "minecraft:orange_tulip",
    "minecraft:oxeye_daisy",
    "minecraft:peony",
    "minecraft:pink_petals",
    "minecraft:pink_tulip",
    "minecraft:poppy",
    "minecraft:red_tulip",
    "minecraft:rose_bush",
    "minecraft:short_grass",
    "minecraft:sunflower",
    "minecraft:tall_grass",
    "minecraft:white_tulip",
    "ribbits:swamp_daisy",
    "rusticdelight:wild_bell_peppers",
    "rusticdelight:wild_coffee",
    "rusticdelight:wild_cotton",
    "ubesdelight:wild_garlic",
    "ubesdelight:wild_ginger",
    "ubesdelight:wild_ube",
    "veggiesdelight:mature_dandelion",
    "veggiesdelight:wild_bellpeppers",
    "veggiesdelight:wild_broccoli",
    "veggiesdelight:wild_cauliflowers",
    "veggiesdelight:wild_garlic",
    "veggiesdelight:wild_sweet_potatoes",
    "veggiesdelight:wild_turnips",
    "veggiesdelight:wild_zucchinis"
]
defaultDensity = 2
ignoredSeasons = "DEFAULT"
fireflyType = "ORIGINAL"
fireflySoundVolume = 1.0
onlyAllowInHabitatBiomes = false
habitatBiomes = [
    "minecraft:swamp",
    "minecraft:mangrove_swamp",
    "biomeswevegone:bayou",
    "biomeswevegone:cypress_swamplands",
    "biomeswevegone:dead_sea"
]
habitatBiomeDensity = 4

[waterfalls]
waterfallsEnabled = true
smallWaterfallsEnabled = true
waterfallUpdateFrequency = 6
randomizeWaterfallParticleRotation = false
mediumWaterfallParticleDensity = 1.0
mediumWaterfallHeightThreshold = 6
forceSpawnMediumWaterfallParticles = true
largeWaterfallsEnabled = true
largeWaterfallParticleDensity = 1.0
largeWaterfallHeightThreshold = 10
forceSpawnLargeWaterfallParticles = true