#This file stores configuration options for Iris, such as the currently active shaderpack
#Sat Feb 07 12:30:19 HST 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=false
maxShadowRenderDistance=0
shaderPack=ComplementaryReimagined_r5.7.1 + EuphoriaPatches_1.8.4
