#This file stores configuration options for Iris, such as the currently active shaderpack
#Mon Apr 06 09:42:09 HST 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=true
enableDebugOptions=false
enableShaders=false
maxShadowRenderDistance=5
shaderPack=ComplementaryReimagined_r5.7.1 + EuphoriaPatches_1.8.6
