#This file stores configuration options for Iris, such as the currently active shaderpack
#Fri Feb 27 10:58:31 HST 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=false
maxShadowRenderDistance=0
shaderPack=ComplementaryReimagined_r5.7.1 + EuphoriaPatches_1.8.6
