/* ══▣ RES INTERFACE ▣═════════════════════════════════════════════════

░░░▒▒▓▓██ RES CORE ██▓▓▒▒░░░

╭────────────────────────────────────────────────────────────────────╮
│ FILE     : 20_cobblemon_picture_quests.js                          │
│ LAYER    : server_scripts                                          │
│ DOMAIN   : progression / quests                                    │
│ PURPOSE  : Cobblemon Advancement Photo Array                       │
│ WARN     : Hardcoded Photo Quest Data to Global                    │
│ UPDATED  : 2026-02-07                                              │
╰────────────────────────────────────────────────────────────────────╯
*/
console.info("[RES:CORE] Initializing 20_cobblemon_picture_quests.js");

global.Photo.quests.push(
  {"advancement": "mayview:photo/caterpie_plains_photo", "biome": "minecraft:plains", "pokemon": "caterpie"},
  {"advancement": "mayview:photo/caterpie_plains_photo", "biome": "minecraft:sunflower_plains", "pokemon": "caterpie"},
  {"advancement": "mayview:photo/caterpie_forest_photo", "biome": "minecraft:forest", "pokemon": "caterpie"},
  {"advancement": "mayview:photo/caterpie_forest_photo", "biome": "minecraft:flower_forest", "pokemon": "caterpie"},
  {"advancement": "mayview:photo/caterpie_forest_photo", "biome": "minecraft:birch_forest", "pokemon": "caterpie"},
  {"advancement": "mayview:photo/caterpie_forest_photo", "biome": "minecraft:old_growth_birch_forest", "pokemon": "caterpie"},
  {"advancement": "mayview:photo/caterpie_forest_photo", "biome": "minecraft:dark_forest", "pokemon": "caterpie"},
  {"advancement": "mayview:photo/metapod_forest_photo", "biome": "minecraft:forest", "pokemon": "metapod"},
  {"advancement": "mayview:photo/metapod_forest_photo", "biome": "minecraft:flower_forest", "pokemon": "metapod"},
  {"advancement": "mayview:photo/metapod_forest_photo", "biome": "minecraft:birch_forest", "pokemon": "metapod"},
  {"advancement": "mayview:photo/metapod_forest_photo", "biome": "minecraft:old_growth_birch_forest", "pokemon": "metapod"},
  {"advancement": "mayview:photo/metapod_forest_photo", "biome": "minecraft:dark_forest", "pokemon": "metapod"},
  {"advancement": "mayview:photo/spewpa_plains_photo", "biome": "minecraft:plains", "pokemon": "spewpa"},
  {"advancement": "mayview:photo/spewpa_plains_photo", "biome": "minecraft:sunflower_plains", "pokemon": "spewpa"},
  {"advancement": "mayview:photo/plusle_plains_photo", "biome": "minecraft:plains", "pokemon": "plusle"},
  {"advancement": "mayview:photo/plusle_plains_photo", "biome": "minecraft:sunflower_plains", "pokemon": "plusle"},
  {"advancement": "mayview:photo/bouffalant_plains_photo", "biome": "minecraft:plains", "pokemon": "bouffalant"},
  {"advancement": "mayview:photo/bouffalant_plains_photo", "biome": "minecraft:sunflower_plains", "pokemon": "bouffalant"},
  {"advancement": "mayview:photo/wooloo_plains_photo", "biome": "minecraft:plains", "pokemon": "wooloo"},
  {"advancement": "mayview:photo/wooloo_plains_photo", "biome": "minecraft:sunflower_plains", "pokemon": "wooloo"},
  {"advancement": "mayview:photo/stonjourner_plains_photo", "biome": "minecraft:plains", "pokemon": "stonjourner"},
  {"advancement": "mayview:photo/stonjourner_plains_photo", "biome": "minecraft:sunflower_plains", "pokemon": "stonjourner"},
  {"advancement": "mayview:photo/electabuzz_plains_photo", "biome": "minecraft:plains", "pokemon": "electabuzz"},
  {"advancement": "mayview:photo/electabuzz_plains_photo", "biome": "minecraft:sunflower_plains", "pokemon": "electabuzz"},
  {"advancement": "mayview:photo/pikachu_forest_photo", "biome": "minecraft:forest", "pokemon": "pikachu"},
  {"advancement": "mayview:photo/pikachu_forest_photo", "biome": "minecraft:flower_forest", "pokemon": "pikachu"},
  {"advancement": "mayview:photo/pikachu_forest_photo", "biome": "minecraft:birch_forest", "pokemon": "pikachu"},
  {"advancement": "mayview:photo/pikachu_forest_photo", "biome": "minecraft:old_growth_birch_forest", "pokemon": "pikachu"},
  {"advancement": "mayview:photo/pikachu_forest_photo", "biome": "minecraft:dark_forest", "pokemon": "pikachu"},
  {"advancement": "mayview:photo/pichu_forest_photo", "biome": "minecraft:forest", "pokemon": "pichu"},
  {"advancement": "mayview:photo/pichu_forest_photo", "biome": "minecraft:flower_forest", "pokemon": "pichu"},
  {"advancement": "mayview:photo/pichu_forest_photo", "biome": "minecraft:birch_forest", "pokemon": "pichu"},
  {"advancement": "mayview:photo/pichu_forest_photo", "biome": "minecraft:old_growth_birch_forest", "pokemon": "pichu"},
  {"advancement": "mayview:photo/pichu_forest_photo", "biome": "minecraft:dark_forest", "pokemon": "pichu"},
  {"advancement": "mayview:photo/raichu_forest_photo", "biome": "minecraft:forest", "pokemon": "raichu"},
  {"advancement": "mayview:photo/raichu_forest_photo", "biome": "minecraft:flower_forest", "pokemon": "raichu"},
  {"advancement": "mayview:photo/raichu_forest_photo", "biome": "minecraft:birch_forest", "pokemon": "raichu"},
  {"advancement": "mayview:photo/raichu_forest_photo", "biome": "minecraft:old_growth_birch_forest", "pokemon": "raichu"},
  {"advancement": "mayview:photo/raichu_forest_photo", "biome": "minecraft:dark_forest", "pokemon": "raichu"},
  {"advancement": "mayview:photo/scyther_forest_photo", "biome": "minecraft:forest", "pokemon": "scyther"},
  {"advancement": "mayview:photo/scyther_forest_photo", "biome": "minecraft:flower_forest", "pokemon": "scyther"},
  {"advancement": "mayview:photo/scyther_forest_photo", "biome": "minecraft:birch_forest", "pokemon": "scyther"},
  {"advancement": "mayview:photo/scyther_forest_photo", "biome": "minecraft:old_growth_birch_forest", "pokemon": "scyther"},
  {"advancement": "mayview:photo/scyther_forest_photo", "biome": "minecraft:dark_forest", "pokemon": "scyther"},
  {"advancement": "mayview:photo/scyther_hills_photo", "biome": "minecraft:windswept_hills", "pokemon": "scyther"},
  {"advancement": "mayview:photo/scyther_hills_photo", "biome": "minecraft:windswept_forest", "pokemon": "scyther"},
  {"advancement": "mayview:photo/scyther_hills_photo", "biome": "minecraft:windswept_gravelly_hills", "pokemon": "scyther"},
  {"advancement": "mayview:photo/scyther_hills_photo", "biome": "minecraft:windswept_savanna", "pokemon": "scyther"},
  {"advancement": "mayview:photo/snorlax_hills_photo", "biome": "minecraft:windswept_hills", "pokemon": "snorlax"},
  {"advancement": "mayview:photo/snorlax_hills_photo", "biome": "minecraft:windswept_forest", "pokemon": "snorlax"},
  {"advancement": "mayview:photo/snorlax_hills_photo", "biome": "minecraft:windswept_gravelly_hills", "pokemon": "snorlax"},
  {"advancement": "mayview:photo/snorlax_hills_photo", "biome": "minecraft:windswept_savanna", "pokemon": "snorlax"},
  {"advancement": "mayview:photo/misdreavus_swamp_photo", "biome": "minecraft:swamp", "pokemon": "misdreavus"},
  {"advancement": "mayview:photo/misdreavus_swamp_photo", "biome": "minecraft:mangrove_swamp", "pokemon": "misdreavus"},
  {"advancement": "mayview:photo/mudkip_swamp_photo", "biome": "minecraft:swamp", "pokemon": "mudkip"},
  {"advancement": "mayview:photo/mudkip_swamp_photo", "biome": "minecraft:mangrove_swamp", "pokemon": "mudkip"},
  {"advancement": "mayview:photo/dondozo_swamp_photo", "biome": "minecraft:swamp", "pokemon": "dondozo"},
  {"advancement": "mayview:photo/dondozo_swamp_photo", "biome": "minecraft:mangrove_swamp", "pokemon": "dondozo"},
  {"advancement": "mayview:photo/magikarp_ocean_photo", "biome": "minecraft:ocean", "pokemon": "magikarp"},
  {"advancement": "mayview:photo/magikarp_ocean_photo", "biome": "minecraft:deep_ocean", "pokemon": "magikarp"},
  {"advancement": "mayview:photo/magikarp_ocean_photo", "biome": "minecraft:cold_ocean", "pokemon": "magikarp"},
  {"advancement": "mayview:photo/magikarp_ocean_photo", "biome": "minecraft:deep_cold_ocean", "pokemon": "magikarp"},
  {"advancement": "mayview:photo/magikarp_ocean_photo", "biome": "minecraft:frozen_ocean", "pokemon": "magikarp"},
  {"advancement": "mayview:photo/magikarp_ocean_photo", "biome": "minecraft:deep_frozen_ocean", "pokemon": "magikarp"},
  {"advancement": "mayview:photo/magikarp_ocean_photo", "biome": "minecraft:lukewarm_ocean", "pokemon": "magikarp"},
  {"advancement": "mayview:photo/magikarp_ocean_photo", "biome": "minecraft:deep_lukewarm_ocean", "pokemon": "magikarp"},
  {"advancement": "mayview:photo/magikarp_ocean_photo", "biome": "minecraft:warm_ocean", "pokemon": "magikarp"},
  {"advancement": "mayview:photo/magikarp_freshwater_photo", "biome": "minecraft:river", "pokemon": "magikarp"},
  {"advancement": "mayview:photo/magikarp_freshwater_photo", "biome": "minecraft:frozen_river", "pokemon": "magikarp"},
  {"advancement": "mayview:photo/bidoof_freshwater_photo", "biome": "minecraft:river", "pokemon": "bidoof"},
  {"advancement": "mayview:photo/bidoof_freshwater_photo", "biome": "minecraft:frozen_river", "pokemon": "bidoof"},
  {"advancement": "mayview:photo/bibarel_freshwater_photo", "biome": "minecraft:river", "pokemon": "bibarel"},
  {"advancement": "mayview:photo/bibarel_freshwater_photo", "biome": "minecraft:frozen_river", "pokemon": "bibarel"},
  {"advancement": "mayview:photo/bibarel_taiga_photo", "biome": "minecraft:taiga", "pokemon": "bibarel"},
  {"advancement": "mayview:photo/bibarel_taiga_photo", "biome": "minecraft:snowy_taiga", "pokemon": "bibarel"},
  {"advancement": "mayview:photo/bibarel_taiga_photo", "biome": "minecraft:old_growth_pine_taiga", "pokemon": "bibarel"},
  {"advancement": "mayview:photo/bibarel_taiga_photo", "biome": "minecraft:old_growth_spruce_taiga", "pokemon": "bibarel"},
  {"advancement": "mayview:photo/talonflame_taiga_photo", "biome": "minecraft:taiga", "pokemon": "talonflame"},
  {"advancement": "mayview:photo/talonflame_taiga_photo", "biome": "minecraft:snowy_taiga", "pokemon": "talonflame"},
  {"advancement": "mayview:photo/geodude_mountain_photo", "biome": "minecraft:meadow", "pokemon": "geodude"},
  {"advancement": "mayview:photo/geodude_mountain_photo", "biome": "minecraft:grove", "pokemon": "geodude"},
  {"advancement": "mayview:photo/geodude_mountain_photo", "biome": "minecraft:snowy_slopes", "pokemon": "geodude"},
  {"advancement": "mayview:photo/geodude_mountain_photo", "biome": "minecraft:jagged_peaks", "pokemon": "geodude"},
  {"advancement": "mayview:photo/geodude_mountain_photo", "biome": "minecraft:frozen_peaks", "pokemon": "geodude"},
  {"advancement": "mayview:photo/geodude_mountain_photo", "biome": "minecraft:stony_peaks", "pokemon": "geodude"},
  {"advancement": "mayview:photo/graveler_mountain_photo", "biome": "minecraft:meadow", "pokemon": "graveler"},
  {"advancement": "mayview:photo/graveler_mountain_photo", "biome": "minecraft:grove", "pokemon": "graveler"},
  {"advancement": "mayview:photo/graveler_mountain_photo", "biome": "minecraft:snowy_slopes", "pokemon": "graveler"},
  {"advancement": "mayview:photo/graveler_mountain_photo", "biome": "minecraft:jagged_peaks", "pokemon": "graveler"},
  {"advancement": "mayview:photo/graveler_mountain_photo", "biome": "minecraft:frozen_peaks", "pokemon": "graveler"},
  {"advancement": "mayview:photo/graveler_mountain_photo", "biome": "minecraft:stony_peaks", "pokemon": "graveler"},
  {"advancement": "mayview:photo/larvitar_mountain_photo", "biome": "minecraft:meadow", "pokemon": "larvitar"},
  {"advancement": "mayview:photo/larvitar_mountain_photo", "biome": "minecraft:grove", "pokemon": "larvitar"},
  {"advancement": "mayview:photo/larvitar_mountain_photo", "biome": "minecraft:snowy_slopes", "pokemon": "larvitar"},
  {"advancement": "mayview:photo/larvitar_mountain_photo", "biome": "minecraft:jagged_peaks", "pokemon": "larvitar"},
  {"advancement": "mayview:photo/larvitar_mountain_photo", "biome": "minecraft:frozen_peaks", "pokemon": "larvitar"},
  {"advancement": "mayview:photo/larvitar_mountain_photo", "biome": "minecraft:stony_peaks", "pokemon": "larvitar"},
  {"advancement": "mayview:photo/tyranitar_mountain_photo", "biome": "minecraft:meadow", "pokemon": "tyranitar"},
  {"advancement": "mayview:photo/tyranitar_mountain_photo", "biome": "minecraft:grove", "pokemon": "tyranitar"},
  {"advancement": "mayview:photo/tyranitar_mountain_photo", "biome": "minecraft:snowy_slopes", "pokemon": "tyranitar"},
  {"advancement": "mayview:photo/tyranitar_mountain_photo", "biome": "minecraft:jagged_peaks", "pokemon": "tyranitar"},
  {"advancement": "mayview:photo/tyranitar_mountain_photo", "biome": "minecraft:frozen_peaks", "pokemon": "tyranitar"},
  {"advancement": "mayview:photo/tyranitar_mountain_photo", "biome": "minecraft:stony_peaks", "pokemon": "tyranitar"},
  {"advancement": "mayview:photo/kommoo_jungle_photo", "biome": "minecraft:jungle", "pokemon": "kommo-o"},
  {"advancement": "mayview:photo/kommoo_jungle_photo", "biome": "minecraft:sparse_jungle", "pokemon": "kommo-o"},
  {"advancement": "mayview:photo/kommoo_jungle_photo", "biome": "minecraft:bamboo_jungle", "pokemon": "kommo-o"},
  {"advancement": "mayview:photo/fuecoco_badlands_photo", "biome": "minecraft:badlands", "pokemon": "fuecoco"},
  {"advancement": "mayview:photo/fuecoco_badlands_photo", "biome": "minecraft:wooded_badlands", "pokemon": "fuecoco"},
  {"advancement": "mayview:photo/fuecoco_badlands_photo", "biome": "minecraft:eroded_badlands", "pokemon": "fuecoco"},
  {"advancement": "mayview:photo/falinks_badlands_photo", "biome": "minecraft:badlands", "pokemon": "falinks"},
  {"advancement": "mayview:photo/falinks_badlands_photo", "biome": "minecraft:wooded_badlands", "pokemon": "falinks"},
  {"advancement": "mayview:photo/falinks_badlands_photo", "biome": "minecraft:eroded_badlands", "pokemon": "falinks"},
  {
    advancement: "mayview:photo/alolan_diglett_beach_photo",
    biome: "minecraft:beach",
    pokemonAny: ["alolan diglett", "diglett (alolan)", "diglett-alola"]
  },
  {
    advancement: "mayview:photo/alolan_diglett_beach_photo",
    biome: "minecraft:snowy_beach",
    pokemonAny: ["alolan diglett", "diglett (alolan)", "diglett-alola"]
  },  
  {
    advancement: "mayview:photo/alolan_diglett_beach_photo",
    biome: "minecraft:stony_shore",
    pokemonAny: ["alolan diglett", "diglett (alolan)", "diglett-alola"]
  },
  {
    advancement: "mayview:photo/alolan_dugtrio_beach_photo",
    biome: "minecraft:beach",
    pokemonAny: ["alolan dugtrio", "dugtrio (alolan)", "dugtrio-alola"]
  },
  {
    advancement: "mayview:photo/alolan_dugtrio_beach_photo",
    biome: "minecraft:snowy_beach",
    pokemonAny: ["alolan dugtrio", "dugtrio (alolan)", "dugtrio-alola"]
  },  
  {
    advancement: "mayview:photo/alolan_dugtrio_beach_photo",
    biome: "minecraft:stony_shore",
    pokemonAny: ["alolan dugtrio", "dugtrio (alolan)", "dugtrio-alola"]
  },
  {
    advancement: "mayview:photo/alolan_muk_beach_photo",
    biome: "minecraft:beach",
    pokemonAny: ["alolan muk", "muk (alolan)", "muk-alola"]
  },
  {
    advancement: "mayview:photo/alolan_muk_beach_photo",
    biome: "minecraft:snowy_beach",
    pokemonAny: ["alolan muk", "muk (alolan)", "muk-alola"]
  },  
  {
    advancement: "mayview:photo/alolan_muk_beach_photo",
    biome: "minecraft:stony_shore",
    pokemonAny: ["alolan muk", "muk (alolan)", "muk-alola"]
  },
  {
    advancement: "mayview:photo/alolan_grimer_beach_photo",
    biome: "minecraft:beach",
    pokemonAny: ["alolan grimer", "grimer (alolan)", "grimer-alola"]
  },
  {
    advancement: "mayview:photo/alolan_grimer_beach_photo",
    biome: "minecraft:snowy_beach",
    pokemonAny: ["alolan grimer", "grimer (alolan)", "grimer-alola"]
  },  
  {
    advancement: "mayview:photo/alolan_grimer_beach_photo",
    biome: "minecraft:stony_shore",
    pokemonAny: ["alolan grimer", "grimer (alolan)", "grimer-alola"]
  },
  {"advancement": "mayview:photo/noibat_spooky_photo", "biome": "minecraft:dark_forest", "pokemon": "noibat"},
  {"advancement": "mayview:photo/noibat_spooky_photo", "biome": "minecraft:deep_dark", "pokemon": "noibat"},
  {"advancement": "mayview:photo/noibat_cave_photo", "biome": "minecraft:lush_caves", "pokemon": "noibat"},
  {"advancement": "mayview:photo/noibat_cave_photo", "biome": "minecraft:dripstone_caves", "pokemon": "noibat"},
  {"advancement": "mayview:photo/noibat_cave_photo", "biome": "minecraft:deep_dark", "pokemon": "noibat"},
  {"advancement": "mayview:photo/noivern_spooky_photo", "biome": "minecraft:dark_forest", "pokemon": "noivern"},
  {"advancement": "mayview:photo/noivern_spooky_photo", "biome": "minecraft:deep_dark", "pokemon": "noivern"},
  {"advancement": "mayview:photo/noivern_cave_photo", "biome": "minecraft:lush_caves", "pokemon": "noivern"},
  {"advancement": "mayview:photo/noivern_cave_photo", "biome": "minecraft:dripstone_caves", "pokemon": "noivern"},
  {"advancement": "mayview:photo/noivern_cave_photo", "biome": "minecraft:deep_dark", "pokemon": "noivern"},
  {"advancement": "mayview:photo/pikipek_forest_photo", "biome": "minecraft:forest", "pokemon": "pikipek"},
  {"advancement": "mayview:photo/pikipek_forest_photo", "biome": "minecraft:flower_forest", "pokemon": "pikipek"},
  {"advancement": "mayview:photo/pikipek_forest_photo", "biome": "minecraft:birch_forest", "pokemon": "pikipek"},
  {"advancement": "mayview:photo/pikipek_forest_photo", "biome": "minecraft:old_growth_birch_forest", "pokemon": "pikipek"},
  {"advancement": "mayview:photo/pikipek_forest_photo", "biome": "minecraft:dark_forest", "pokemon": "pikipek"},
  {"advancement": "mayview:photo/pikipek_jungle_photo", "biome": "minecraft:jungle", "pokemon": "pikipek"},
  {"advancement": "mayview:photo/pikipek_jungle_photo", "biome": "minecraft:sparse_jungle", "pokemon": "pikipek"},
  {"advancement": "mayview:photo/pikipek_jungle_photo", "biome": "minecraft:bamboo_jungle", "pokemon": "pikipek"},
  {"advancement": "mayview:photo/pikipek_taiga_photo", "biome": "minecraft:taiga", "pokemon": "pikipek"},
  {"advancement": "mayview:photo/pikipek_taiga_photo", "biome": "minecraft:snowy_taiga", "pokemon": "pikipek"},
  {"advancement": "mayview:photo/pikipek_taiga_photo", "biome": "minecraft:old_growth_pine_taiga", "pokemon": "pikipek"},
  {"advancement": "mayview:photo/pikipek_taiga_photo", "biome": "minecraft:old_growth_spruce_taiga", "pokemon": "pikipek"},
  {"advancement": "mayview:photo/trumbeak_forest_photo", "biome": "minecraft:forest", "pokemon": "trumbeak"},
  {"advancement": "mayview:photo/trumbeak_forest_photo", "biome": "minecraft:flower_forest", "pokemon": "trumbeak"},
  {"advancement": "mayview:photo/trumbeak_forest_photo", "biome": "minecraft:birch_forest", "pokemon": "trumbeak"},
  {"advancement": "mayview:photo/trumbeak_forest_photo", "biome": "minecraft:old_growth_birch_forest", "pokemon": "trumbeak"},
  {"advancement": "mayview:photo/trumbeak_forest_photo", "biome": "minecraft:dark_forest", "pokemon": "trumbeak"},
  {"advancement": "mayview:photo/trumbeak_jungle_photo", "biome": "minecraft:jungle", "pokemon": "trumbeak"},
  {"advancement": "mayview:photo/trumbeak_jungle_photo", "biome": "minecraft:sparse_jungle", "pokemon": "trumbeak"},
  {"advancement": "mayview:photo/trumbeak_jungle_photo", "biome": "minecraft:bamboo_jungle", "pokemon": "trumbeak"},
  {"advancement": "mayview:photo/trumbeak_taiga_photo", "biome": "minecraft:taiga", "pokemon": "trumbeak"},
  {"advancement": "mayview:photo/trumbeak_taiga_photo", "biome": "minecraft:snowy_taiga", "pokemon": "trumbeak"},
  {"advancement": "mayview:photo/trumbeak_taiga_photo", "biome": "minecraft:old_growth_pine_taiga", "pokemon": "trumbeak"},
  {"advancement": "mayview:photo/trumbeak_taiga_photo", "biome": "minecraft:old_growth_spruce_taiga", "pokemon": "trumbeak"},
  {"advancement": "mayview:photo/toucannon_forest_photo", "biome": "minecraft:forest", "pokemon": "toucannon"},
  {"advancement": "mayview:photo/toucannon_forest_photo", "biome": "minecraft:flower_forest", "pokemon": "toucannon"},
  {"advancement": "mayview:photo/toucannon_forest_photo", "biome": "minecraft:birch_forest", "pokemon": "toucannon"},
  {"advancement": "mayview:photo/toucannon_forest_photo", "biome": "minecraft:old_growth_birch_forest", "pokemon": "toucannon"},
  {"advancement": "mayview:photo/toucannon_forest_photo", "biome": "minecraft:dark_forest", "pokemon": "toucannon"},
  {"advancement": "mayview:photo/toucannon_jungle_photo", "biome": "minecraft:jungle", "pokemon": "toucannon"},
  {"advancement": "mayview:photo/toucannon_jungle_photo", "biome": "minecraft:sparse_jungle", "pokemon": "toucannon"},
  {"advancement": "mayview:photo/toucannon_jungle_photo", "biome": "minecraft:bamboo_jungle", "pokemon": "toucannon"},
  {"advancement": "mayview:photo/toucannon_taiga_photo", "biome": "minecraft:taiga", "pokemon": "toucannon"},
  {"advancement": "mayview:photo/toucannon_taiga_photo", "biome": "minecraft:snowy_taiga", "pokemon": "toucannon"},
  {"advancement": "mayview:photo/toucannon_taiga_photo", "biome": "minecraft:old_growth_pine_taiga", "pokemon": "toucannon"},
  {"advancement": "mayview:photo/toucannon_taiga_photo", "biome": "minecraft:old_growth_spruce_taiga", "pokemon": "toucannon"},
  {"advancement": "mayview:photo/rockruff_taiga_photo", "biome": "minecraft:taiga", "pokemon": "rockruff"},
  {"advancement": "mayview:photo/rockruff_taiga_photo", "biome": "minecraft:snowy_taiga", "pokemon": "rockruff"},
  {"advancement": "mayview:photo/rockruff_taiga_photo", "biome": "minecraft:old_growth_pine_taiga", "pokemon": "rockruff"},
  {"advancement": "mayview:photo/rockruff_taiga_photo", "biome": "minecraft:old_growth_spruce_taiga", "pokemon": "rockruff"},
  {"advancement": "mayview:photo/lycanroc_hills_photo", "biome": "minecraft:windswept_hills", "pokemon": "lycanroc"},
  {"advancement": "mayview:photo/lycanroc_hills_photo", "biome": "minecraft:windswept_forest", "pokemon": "lycanroc"},
  {"advancement": "mayview:photo/lycanroc_hills_photo", "biome": "minecraft:windswept_gravelly_hills", "pokemon": "lycanroc"},
  {"advancement": "mayview:photo/lycanroc_hills_photo", "biome": "minecraft:windswept_savanna", "pokemon": "lycanroc"},
  {"advancement": "mayview:photo/combee_orchard_photo", "biome": "biomeswevegone:orchard", "pokemon": "combee" },
  {"advancement": "mayview:photo/scraggy_red_rock_valley_photo", "biome": "biomeswevegone:red_rock_valley", "pokemon": "scraggy" },
  {"advancement": "mayview:photo/beedrill_crag_gardens_photo", "biome": "biomeswevegone:crag_gardens", "pokemon": "beedrill" },
  {"advancement": "mayview:photo/buneary_orchard_photo", "biome": "biomeswevegone:orchard", "pokemon": "buneary" },
  {"advancement": "mayview:photo/rhyhorn_ironwood_gour_photo", "biome": "biomeswevegone:ironwood_gour", "pokemon": "rhyhorn" }
);