ServerEvents.recipes(event => {
  const MYTH_DUPES = [
    "mythsandlegends:adamant_orb",
    "mythsandlegends:ancient_tablet",
    "mythsandlegends:antique_pokeball",
    "mythsandlegends:aurora_ticket",
    "mythsandlegends:azelf_fang",
    "mythsandlegends:azure_flute",
    "mythsandlegends:binding_mochi",
    "mythsandlegends:blue_orb",
    "mythsandlegends:bonus_disk",
    "mythsandlegends:bulu_totem",
    "mythsandlegends:cavern_shield",
    "mythsandlegends:clear_bell",
    "mythsandlegends:cocoon_of_destruction",
    "mythsandlegends:cornerstone_mask",
    "mythsandlegends:dark_stone",
    "mythsandlegends:diancies_crown",
    "mythsandlegends:dna_splicer",
    "mythsandlegends:dr_fujis_diary",
    "mythsandlegends:eon_ticket",
    "mythsandlegends:eternatus_core",
    "mythsandlegends:fini_totem",
    "mythsandlegends:genesect_drive",
    "mythsandlegends:grassland_blade",
    "mythsandlegends:griseous_orb",
    "mythsandlegends:gs_ball",
    "mythsandlegends:hearthflame_mask",
    "mythsandlegends:hoopa_ring",
    "mythsandlegends:ice_tablet",
    "mythsandlegends:iceroot_carrot",
    "mythsandlegends:ironwill_sword",
    "mythsandlegends:jade_orb",
    "mythsandlegends:koko_totem",
    "mythsandlegends:kubfus_band",
    "mythsandlegends:lele_totem",
    "mythsandlegends:liberty_pass",
    "mythsandlegends:light_stone",
    "mythsandlegends:lillies_bag",
    "mythsandlegends:lunar_feather",
    "mythsandlegends:lustrous_orb",
    "mythsandlegends:magma_stone",
    "mythsandlegends:marshadow_hood",
    "mythsandlegends:meloetta_headset",
    "mythsandlegends:member_card",
    "mythsandlegends:mesprit_plume",
    "mythsandlegends:moon_flute",
    "mythsandlegends:mystery_box",
    "mythsandlegends:mythical_pecha_berry",
    "mythsandlegends:necro_prism",
    "mythsandlegends:oaks_letter",
    "mythsandlegends:old_sea_map",
    "mythsandlegends:plasma_tablet",
    "mythsandlegends:prismatic_shell",
    "mythsandlegends:prison_bottle",
    "mythsandlegends:rainbow_wing",
    "mythsandlegends:red_orb",
    "mythsandlegends:reins_of_unity",
    "mythsandlegends:reveal_glass",
    "mythsandlegends:rusted_shield",
    "mythsandlegends:rusted_sword",
    "mythsandlegends:sacred_sword",
    "mythsandlegends:sapling_of_life",
    "mythsandlegends:scaly_tablet",
    "mythsandlegends:scarlet_book",
    "mythsandlegends:scroll_of_darkness",
    "mythsandlegends:scroll_of_water",
    "mythsandlegends:shaderoot_carrot",
    "mythsandlegends:silver_wing",
    "mythsandlegends:soul_heart",
    "mythsandlegends:steam_valve",
    "mythsandlegends:steel_tablet",
    "mythsandlegends:stone_tablet",
    "mythsandlegends:sun_flute",
    "mythsandlegends:teal_mask",
    "mythsandlegends:tidal_bell",
    "mythsandlegends:type_null_mask",
    "mythsandlegends:uxie_claw",
    "mythsandlegends:violet_book",
    "mythsandlegends:wellspring_mask",
    "mythsandlegends:zarudes_cape",
    "mythsandlegends:zeraoras_thunderclaw"
  ]

  const pattern = [
    'CGC',
    'DID',
    'HGH'
  ]

  MYTH_DUPES.forEach(itemId => {
    const path = itemId.split(':')[1]

    event.shaped(
      Item.of(itemId, 2),
      pattern,
      {
        C: 'cobblemon:exp_candy_l',
        D: 'minecraft:diamond',
        G: 'minecraft:enchanted_golden_apple',
        H: 'cobblemonraiddens:cheer_heal',
        I: Ingredient.of(itemId)
      }
    ).id(`mayview:duplicate/myths_and_legends/${path}`)
  })
})